import { ImageResponse } from "next/og";

// GET /api/og?title=Anything  →  1200×630 PNG
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const title = (searchParams.get("title") ?? "USACS × Vercel").slice(0, 80);

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: 64,
          background: "linear-gradient(135deg, #cc0033 0%, #111 55%, #0070f3 100%)",
          color: "white",
        }}
      >
        <div style={{ fontSize: 32, opacity: 0.8 }}>▲ Rutgers USACS · Fall 2026</div>
        <div style={{ fontSize: 88, fontWeight: 700, lineHeight: 1.1 }}>{title}</div>
        <div style={{ fontSize: 28, opacity: 0.8 }}>Generated by next/og</div>
      </div>
    ),
    { width: 1200, height: 630 },
  );
}
